name: Build .deb Package

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Docker ile Build et
      run: |
        docker build -f docker/Dockerfile -t mte-toolbox-builder .

    - name: .deb dosyasını konteynerden çıkar
      run: |
        container_id=$(docker create mte-toolbox-builder)
        docker cp $container_id:/src/build ./build
        docker rm $container_id

    - name: Build çıktısını kontrol et
      run: ls -l build/

    - name: Build çıktısını artifact olarak kaydet
      uses: actions/upload-artifact@v4
      with:
        name: mte-toolbox-deb
        path: build/*.deb

  test-artifact-download:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Artifact'ı indir
      uses: actions/download-artifact@v4
      with:
        name: mte-toolbox-deb
        path: downloaded-debs
        merge-multiple: true  # Aynı klasöre indir

