name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Sadece 'v1.2.3' gibi versiyon tag'leriyle çalışır

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # GitHub Release oluşturmak için gerekli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from Git tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build Docker image and extract .deb package
        run: |
          echo "🔧 Versiyon: ${VERSION}"
          docker build --build-arg VERSION=${VERSION} -t ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:${VERSION} .
          docker create --name mte_temp_container ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:${VERSION}
          docker cp mte_temp_container:/app/build/*.deb .
          docker rm mte_temp_container
          DEB_FILE=$(ls *.deb | head -n1)
          echo "DEB_FILE=${DEB_FILE}" >> $GITHUB_ENV

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mte-toolbox-deb-package
          path: ${{ env.DEB_FILE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:${VERSION}
          docker tag ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:${VERSION} ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.DEB_FILE }}
          generate_release_notes: true
