name: Build Docker Image

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v.1.0.0'

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image and create .deb package
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:build_temp .

          docker run --name mte_temp_container ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:build_temp /bin/true

          DEB_FILE=$(docker exec mte_temp_container find /src/build -name "*.deb" -print -quit)
          if [ -z "$DEB_FILE" ]; then
            echo "Error: .deb file not found in container."
            exit "
          fi
          docker cp mte_temp_container:$DEB_FILE .

          docker rm mte_temp_container
        working-directory: ${{ github.workspace }}

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !startsWith(github.ref 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mte-toolbox-builder:latest
      - name: Create GitHbu Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/actions-gh-release@v2
        with:
           files: ${{ github.workspace }}/$(basename $DEB_FILE)
           generate_release_notes: true
