name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: 'linux'
          target: 'desktop'

      - name: Build Docker image
        run: docker build -t mte-toolbox-build .

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/build mte-toolbox-build /bin/bash -c "
            mkdir -p /build/build && \
            cd /build/build && \
            cmake .. -DCMAKE_BUILD_TYPE=Release && \
            make -j$(nproc) && \
            cpack -G DEB && \
            cp mte-toolbox-*.deb /build/
          "

      - name: List build output (debugging)
        run: ls -al ./build

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: mte-toolbox
          path: ./build/mte-toolbox-*.deb
          if-no-files-found: warn
