name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.8.3'
          host: 'linux'
          target: 'desktop'

      - name: Build Docker image
        run: docker build -t mte-toolbox-build .

      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}:/build mte-toolbox-build

      - name: Upload DEB package
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mte-toolbox
          path: ./build/*.deb
