name: Build .deb Package

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Docker ile Build et
      run: |
        docker build -t mte-toolbox-builder .

    - name: .deb dosyasını konteynerden çıkar
      run: |
        container_id=$(docker create mte-toolbox-builder)
        docker cp $container_id:/src/build ./
        docker rm $container_id

    - name: Build çıktısını artifact olarak kaydet
      uses: actions/upload-artifact@v3
      with:
        name: mte-toolbox-deb
        path: build/*.deb

